
import { Question, Severity, Language } from './types';

export const QUESTIONS: Question[] = [
  // MOOD (Framed from PHQ-9)
  { id: 'p1', category: 'mood', text: { en: 'Feeling like you just don’t have the heart for the things you usually love?', es: '¿Sientes que ya no tienes las mismas ganas de hacer las cosas que antes te gustaban?' } },
  { id: 'p2', category: 'mood', text: { en: 'Feeling heavy, down, or like you’re just going through the motions?', es: '¿Te sientes desanimado/a, triste o como si estuvieras en piloto automático?' } },
  { id: 'p3', category: 'mood', text: { en: 'Sleep is all over the place—either staying up too late or wanting to sleep the whole day?', es: '¿Tu sueño está fatal—o te desvelas mucho o quieres pasar todo el día dumiendo?' } },
  { id: 'p4', category: 'mood', text: { en: 'Feeling drained, like your battery is at 1% even after a rest?', es: '¿Te sientes sin pilas, como si tu energía estuviera al mínimo aunque descanses?' } },
  { id: 'p5', category: 'mood', text: { en: 'Eating way more than usual or just not having an appetite at all?', es: '¿Estás comiendo por ansiedad o se te ha ido el hambre por completo?' } },
  { id: 'p6', category: 'mood', text: { en: 'Feeling like you’re letting people down, or not living up to who you want to be?', es: '¿Sientes que les estás fallando a los tuyos o que no estás dando la talla?' } },
  { id: 'p7', category: 'mood', text: { en: 'Mind is wandering, having a hard time focusing on one thing at a time?', es: '¿Sientes que tu mente vuela y te cuesta mucho concentrarte en una sola cosa?' } },
  { id: 'p8', category: 'mood', text: { en: 'Feeling super restless or the opposite—moving way slower than your normal pace?', es: '¿Te sientes demasiado inquieto/a o, al revés, sientes que te mueves en cámara lenta?' } },
  { id: 'p9', category: 'mood', text: { en: 'Having scary thoughts about hurting yourself or like it would be easier if you weren’t here?', es: '¿Has tenido pensamientos de hacerte daño o sientes que sería más fácil si ya no estuvieras?' } },
  
  // ANXIETY (Framed from GAD-7)
  { id: 'g1', category: 'anxiety', text: { en: 'Feeling restless, on edge, or like your nerves are shot?', es: '¿Sientes los nervios de punta, inquietud o una sensación de intranquilidad?' } },
  { id: 'g2', category: 'anxiety', text: { en: 'Can’t seem to turn off the "what-ifs" or control the worrying?', es: '¿Sientes que no puedes apagar la cabeza o dejar de darle vueltas a las cosas?' } },
  { id: 'g3', category: 'anxiety', text: { en: 'Worrying about so many different things all at once?', es: '¿Te preocupas por demasiadas cosas al mismo tiempo?' } },
  { id: 'g4', category: 'anxiety', text: { en: 'Finding it impossible to just sit still and relax your mind?', es: '¿Sientes que es imposible desconectarte y relajar la mente un rato?' } },
  { id: 'g5', category: 'anxiety', text: { en: 'Being so restless that you’re constantly moving around or fidgeting?', es: '¿Estás tan inquieto/a que no puedes ni quedarte sentado/a?' } },
  { id: 'g6', category: 'anxiety', text: { en: 'Getting annoyed or losing your cool way faster than usual?', es: '¿Sientes que te irritas o pierdes la paciencia mucho más rápido que antes?' } },
  { id: 'g7', category: 'anxiety', text: { en: 'Feeling a sense of dread, like something bad is about to go down?', es: '¿Sientes un miedo feo, como si algo terrible estuviera a punto de suceder?' } }
];

export const STRINGS = {
  en: {
    title: 'THE VIBE CHECK',
    subtitle: 'Protecting your peace starts here.',
    intro: 'No doctor talk, just real questions. Takes 3 minutes to see where your head is at.',
    start: 'Check My Vibe',
    checkYourself: 'Check Yourself Tool',
    backToClinic: 'Back to healthmatters.clinic',
    disclaimer: 'This tool is for screening purposes only and is NOT a clinical diagnosis. It does not replace professional medical or mental health care. If you are in immediate danger, call 911 or 988.',
    lifeEventTitle: 'Big Transitions',
    lifeEventSub: 'Sometimes the vibe shifts because of what life is throwing at you. Have any of these happened recently?',
    rootCauseTitle: 'The Heavy Load',
    rootCauseSub: 'Is everyday survival making things harder? Check any of these that you are currently dealing with.',
    rootCauseNext: 'Get My Report',
    resultsHeader: 'Your Energy Report',
    doctorSpeakHeader: 'Talking to a Professional',
    doctorSpeakIntro: 'When you talk to a professional, you can share these results. Here is how they might "translate" what you are feeling:',
    communityHeader: 'Community & Connections',
    communitySub: 'You are Unstoppable. Join a wellness meetup, walk, or workshop to build the best version of you.',
    eventLink: 'Join an Event',
    recsHeader: 'Protecting Your Peace',
    crisisTitle: 'We See You',
    crisisSub: 'If the weight feels too heavy right now, someone is ready to listen 24/7.',
    call988: 'Text or Call 988',
    back: 'Back',
    next: 'Next',
    finish: 'Share',
    restart: 'Restart',
    download: 'Save Results',
    share: 'Share Results',
    gamePlanBtn: 'Build My Game Plan',
    gamePlanSub: 'Your Recovery Play',
    resourceBtn: 'Resource Directory',
    resourceSub: 'Community Partners',
    podcastBtn: 'Unboxed Series',
    podcastSub: 'Real community stories.',
    blogBtn: 'The Pulse',
    blogSub: 'Monthly newsletter and health stories.',
    overLast2Weeks: 'Thinking about the last 2 weeks... how much does this sound like you?',
    moodLabel: 'Mood Check',
    anxietyLabel: 'Calm Check',
    lookoutTitle: 'Be on the lookout!',
    lookoutSub: 'We have your choices saved. Be on the lookout for more info from the HMC team.',
    clinicalInterpretation: 'Clinical Interpretation',
    patientAdvocacyScript: 'Patient Advocacy Script:',
    stayConnectedTitle: 'Stay Connected with HMC',
    connectedMessage: "YOU'RE CONNECTED!",
    smsCheckInLabel: 'HMC SMS Check-ins',
    appMemberLabel: 'HMC Member App',
    optInWellness: 'OPT-IN FOR WELLNESS',
    referralServices: 'REFERRAL SERVICES',
    identifiedLifeContext: 'Identified Life Context',
    lifeContextSub: 'Wellbeing is tied to your environment. You mentioned dealing with:',
    calmKitTitle: 'Need a Reset Right Now?',
    calmKitSub: 'Access the Calm Kit for guided breathing, audio resets, and meditations to help you settle into your peace.',
    calmKitBtn: 'GET STARTED IMMEDIATELY',
    returnDashboard: 'Return to Start',
    contextHeader: 'Context: The Big Picture',
    environmentHeader: 'Environment: External Stressors',
    severityMap: {
      'minimal': 'Doing Alright',
      'mild': 'Feeling a Bit Heavy',
      'moderate': 'The Weight is Building',
      'moderately-severe': 'Tough Season',
      'severe': 'Time for Community Care'
    },
    gpPart: 'Part',
    gpStrategy: 'Your Strategy',
    gpInventoryTitle: 'Inventory',
    gpGroundingLabel: 'What grounds you?',
    gpGroundingPlaceholder: 'A song, quote, or reminder...',
    gpToolsLabel: 'Daily Tools:',
    gpStabilizeTitle: 'Stabilize',
    gpContactsLabel: 'Support Contacts (Ride or Die):',
    gpNamePlaceholder: 'Name',
    gpPhonePlaceholder: 'Phone',
    gpResetTitle: 'Reset',
    gpPlaylistLabel: 'Playlist or Creative Outlet:',
    gpPlaylistPlaceholder: 'Music that shifts your mood...',
    gpCreativePlaceholder: 'Art, cooking, dance...',
    gpPhysicalLabel: 'Physical Reset:',
    gpPhysicalPlaceholder: 'A walk, workout, stretch...',
    gpReconnectTitle: 'Reconnect',
    gpForwardLabel: 'One thing looking forward to:',
    gpForwardPlaceholder: 'Next week or next month...',
    gpMessageLabel: 'Note to future self:',
    gpMessagePlaceholder: 'What do you need to hear when it\'s dark?',
    gpCommunityTitle: 'HMC Community Connection',
    gpSmsConsent: 'HMC cares about your wellbeing—can we check in on you?',
    gpAppConsent: 'Join for priority referral support and community insights',
    gpContinue: 'Continue',
    gpFinish: 'Share',
    gpResultsHeader: 'MY RECOVERY PLAY',
    gpResultsSub: 'Built with Health Matters Clinic',
    gpResultsGrounding: 'Grounding Point',
    gpResultsEmergency: 'Emergency Support',
    gpResultsStrategies: 'Daily Strategies',
    gpResultsMessage: 'Message to self',
    gpResultsPrimary: 'Primary Support',
    gpResultsSecondary: 'Secondary Support',
    gpResultsGroundingText: 'I am worth the effort.',
    gpResultsStrategiesText: 'Breathe, move, reset.',
    gpResultsMessageText: 'You are unstoppable.',
    thanksSubscribing: "Thanks for subscribing—we'll be reaching out!",
    sharePlan: 'Share Plan',
    calmKitPageTitle: 'Your Calm Kit',
    calmKitPageSub: 'Take a moment. You earned it.',
    calmKitBreathingBtn: 'Breathing Break',
    calmKitBreathingSub: '4-count box breathing to slow your system down.',
    calmKitGroundingBtn: '5-4-3-2-1 Grounding',
    calmKitGroundingSub: 'Anchor yourself in the present moment.',
    calmKitBreathIn: 'Breathe In',
    calmKitHold: 'Hold',
    calmKitBreathOut: 'Breathe Out',
    calmKitBackToResults: 'Back to Results',
    calmKitDone: 'Nice Work',
    calmKitDoneSub: 'Remember: you can come back to this anytime.',
    groundingSee: 'things you can SEE',
    groundingTouch: 'things you can TOUCH',
    groundingHear: 'things you can HEAR',
    groundingSmell: 'things you can SMELL',
    groundingTaste: 'thing you can TASTE',
    downloadResults: 'Save Results',
    resumePrompt: 'You have a check-in progress saved. Want to pick up where you left off?',
    resumeYes: 'Continue',
    resumeNo: 'Start Fresh',
    gpTherapistLabel: 'Therapist or Support Group:',
    gpTherapistPlaceholder: 'Name of therapist, counselor, or group...',
    gpCrisisNote: 'Always accessible — no matter what:',
    gpResultsTherapist: 'Professional Support',
    gpResultsTools: 'Daily Tools',
    gpResultsLookingForward: 'Looking Forward To',
    gpResultsIntro: 'This is your go-to guide when things get heavy. Keep it close — screenshot it, print it, or save it.',
    gpBeginReferral: 'Begin A Referral',
    gpReferralSub: 'Connect with an HMC team member for personalized support',
    gpResultsCreative: 'Creative Outlet',
    gpResultsPlaylist: 'Playlist / Music'
  },
  es: {
    title: 'EL DESAHOGO',
    subtitle: 'Tu paz mental es lo primero.',
    intro: 'Sin términos médicos raros, solo preguntas reales. Toma unos 3 minutos ver cómo anda tu energía.',
    start: 'Empezar el Chequeo',
    checkYourself: 'Herramienta Check Yourself',
    backToClinic: 'Volver a healthmatters.clinic',
    disclaimer: 'Esta herramienta es solo para detección y NO es un diagnóstico clínico. No reemplaza la atención médica o mental profesional. Si está en peligro inmediato, llame al 911 o al 988.',
    lifeEventTitle: 'Cambios Fuertes',
    lifeEventSub: 'A veces el ánimo cambia por lo que la vida nos lanza. ¿Te ha pasado algo de esto recientemente?',
    rootCauseTitle: 'La Carga Pesada',
    rootCauseSub: '¿La lucha del día a día está dificultando las cosas? Marca lo que estés enfrentando hoy.',
    rootCauseNext: 'Ver Mi Reporte',
    resultsHeader: 'Tu Reporte de Energía',
    doctorSpeakHeader: 'Hablando con un Profesional',
    doctorSpeakIntro: 'Cuando hables con un profesional, puedes mostrarle esto. Así es como ellos "traducen" lo que sientes:',
    communityHeader: 'Comunidad y Conexión',
    communitySub: 'Eres imparable. Únete a una caminata, taller o reunión de bienestar para ser tu mejor versión.',
    eventLink: 'Ver Eventos',
    recsHeader: 'Protegiendo Tu Paz',
    crisisTitle: 'No Estás Solo/a',
    crisisSub: 'Si sientes que ya no puedes más, hay alguien listo para escucharte 24/7.',
    call988: 'Llama o Texto al 988',
    back: 'Atrás',
    next: 'Siguiente',
    finish: 'Compartir',
    restart: 'Reiniciar',
    download: 'Guardar Resultados',
    share: 'Compartir Resultados',
    gamePlanBtn: 'Crear Plan de Juego',
    gamePlanSub: 'Tu Estrategia de Bienestar',
    resourceBtn: 'Directorio de Recursos',
    resourceSub: 'Socios en la Comunidad',
    podcastBtn: 'Serie Unboxed',
    podcastSub: 'Historias reales de la comunidad.',
    blogBtn: 'El Pulso',
    blogSub: 'Noticias e historias de salud.',
    overLast2Weeks: 'Pensando en las últimas 2 semanas... ¿qué tanto te suena esto?',
    moodLabel: 'Chequeo del Ánimo',
    anxietyLabel: 'Chequeo de la Calma',
    lookoutTitle: '¡Mantente pendiente!',
    lookoutSub: 'Ya guardamos tus preferencias. Esté atento a más información del equipo de HMC.',
    clinicalInterpretation: 'Interpretación Clínica',
    patientAdvocacyScript: 'Guion de Defensa del Paciente:',
    stayConnectedTitle: 'Mantente Conectado con HMC',
    connectedMessage: "¡YA ESTÁS CONECTADO/A!",
    smsCheckInLabel: 'Mensajes de Bienestar de HMC',
    appMemberLabel: 'App de Miembros de HMC',
    optInWellness: 'INSRÍBETE PARA BIENESTAR',
    referralServices: 'SERVICIOS DE REFERENCIA',
    identifiedLifeContext: 'Contexto de Vida Identificado',
    lifeContextSub: 'El bienestar está ligado a tu entorno. Mencionaste estar lidiando con:',
    calmKitTitle: '¿Necesitas Reiniciarte Ahora Mismo?',
    calmKitSub: 'Accede al Calm Kit para respiración guiada, reinicios de audio y meditaciones para ayudarte a encontrar tu paz.',
    calmKitBtn: 'EMPEZAR AHORA MISMO',
    returnDashboard: 'Volver al Inicio',
    contextHeader: 'Contexto: El Panorama General',
    environmentHeader: 'Ambiente: Estresores Externos',
    severityMap: {
      'minimal': 'Todo Bien por Ahora',
      'mild': 'Un Poco Pesado',
      'moderate': 'La Carga está Pesando',
      'moderately-severe': 'Temporada Difícil',
      'severe': 'Hora de Buscar Apoyo'
    },
    gpPart: 'Parte',
    gpStrategy: 'Tu Estrategia',
    gpInventoryTitle: 'Inventario',
    gpGroundingLabel: '¿Qué te mantiene firme?',
    gpGroundingPlaceholder: 'Una canción, frase, o recordatorio...',
    gpToolsLabel: 'Herramientas Diarias:',
    gpStabilizeTitle: 'Estabilizar',
    gpContactsLabel: 'Contactos de Apoyo (Tu Gente de Confianza):',
    gpNamePlaceholder: 'Nombre',
    gpPhonePlaceholder: 'Teléfono',
    gpResetTitle: 'Reiniciar',
    gpPlaylistLabel: 'Playlist o Desahogo Creativo:',
    gpPlaylistPlaceholder: 'Música que cambia tu ánimo...',
    gpCreativePlaceholder: 'Arte, cocina, baile...',
    gpPhysicalLabel: 'Reinicio Físico:',
    gpPhysicalPlaceholder: 'Una caminata, ejercicio, estiramiento...',
    gpReconnectTitle: 'Reconectar',
    gpForwardLabel: 'Algo que esperas con ganas:',
    gpForwardPlaceholder: 'La próxima semana o mes...',
    gpMessageLabel: 'Nota para tu "yo" del futuro:',
    gpMessagePlaceholder: '¿Qué necesitas escuchar cuando todo se vea oscuro?',
    gpCommunityTitle: 'Conexión Comunitaria HMC',
    gpSmsConsent: 'HMC se preocupa por ti—¿podemos chequear cómo estás?',
    gpAppConsent: 'Apoyo prioritario y conexión comunitaria',
    gpContinue: 'Continuar',
    gpFinish: 'Compartir',
    gpResultsHeader: 'MI PLAN DE RECUPERACIÓN',
    gpResultsSub: 'Creado con Health Matters Clinic',
    gpResultsGrounding: 'Punto de Apoyo',
    gpResultsEmergency: 'Apoyo de Emergencia',
    gpResultsStrategies: 'Estrategias Diarias',
    gpResultsMessage: 'Mensaje para mí',
    gpResultsPrimary: 'Apoyo Primario',
    gpResultsSecondary: 'Apoyo Secundario',
    gpResultsGroundingText: 'Merezco el esfuerzo.',
    gpResultsStrategiesText: 'Respira, muévete, reinicia.',
    gpResultsMessageText: 'Eres imparable.',
    thanksSubscribing: "¡Gracias por suscribirte—nos pondremos en contacto!",
    sharePlan: 'Compartir Plan',
    calmKitPageTitle: 'Tu Kit de Calma',
    calmKitPageSub: 'Tómate un momento. Te lo ganaste.',
    calmKitBreathingBtn: 'Pausa de Respiración',
    calmKitBreathingSub: 'Respiración de caja de 4 tiempos para bajar las revoluciones.',
    calmKitGroundingBtn: 'Anclaje 5-4-3-2-1',
    calmKitGroundingSub: 'Anclarte en el momento presente.',
    calmKitBreathIn: 'Inhala',
    calmKitHold: 'Sostén',
    calmKitBreathOut: 'Exhala',
    calmKitBackToResults: 'Volver a Resultados',
    calmKitDone: 'Buen Trabajo',
    calmKitDoneSub: 'Recuerda: puedes volver aquí cuando quieras.',
    groundingSee: 'cosas que puedes VER',
    groundingTouch: 'cosas que puedes TOCAR',
    groundingHear: 'cosas que puedes OÍR',
    groundingSmell: 'cosas que puedes OLER',
    groundingTaste: 'cosa que puedes SABOREAR',
    downloadResults: 'Guardar Resultados',
    resumePrompt: 'Tienes un chequeo guardado. ¿Quieres continuar donde lo dejaste?',
    resumeYes: 'Continuar',
    resumeNo: 'Empezar de Nuevo',
    gpTherapistLabel: 'Terapeuta o Grupo de Apoyo:',
    gpTherapistPlaceholder: 'Nombre de terapeuta, consejero, o grupo...',
    gpCrisisNote: 'Siempre accesible — pase lo que pase:',
    gpResultsTherapist: 'Apoyo Profesional',
    gpResultsTools: 'Herramientas Diarias',
    gpResultsLookingForward: 'Lo Que Espero',
    gpResultsIntro: 'Esta es tu guía para cuando las cosas se pongan pesadas. Tenla cerca — tómale foto, imprímela, o guárdala.',
    gpBeginReferral: 'Iniciar Una Referencia',
    gpReferralSub: 'Conecta con un miembro del equipo de HMC para apoyo personalizado',
    gpResultsCreative: 'Desahogo Creativo',
    gpResultsPlaylist: 'Playlist / Música'
  }
};

export const INTERPRETATIONS = {
  mood: {
    minimal: { 
        en: 'You’re holding it down. Keep prioritizing your self-care routines.', 
        es: 'La llevas bien. Sigue dándole prioridad a tus momentos de descanso.',
        clinical: { en: 'Minimal depressive symptoms.', es: 'Síntomas depresivos mínimos.' }
    },
    mild: { 
        en: 'You might be carrying a little extra stress. Maybe it’s time to say "no" to something and "yes" to yourself.', 
        es: 'Parece que traes un poco de carga extra. Quizás es hora de soltar algo y darte un respiro.',
        clinical: { en: 'Mild symptoms of low mood/depression.', es: 'Síntomas leves de depresión o bajo ánimo.' }
    },
    moderate: { 
        en: 'The weight is getting real. Talking to a therapist who "gets it" could really help.', 
        es: 'La cosa se está poniendo pesada. Hablar con alguien que te entienda de verdad te puede ayudar.',
        clinical: { en: 'Moderate depressive symptoms. Clinical evaluation suggested.', es: 'Síntomas depresivos moderados. Se sugiere evaluación clínica.' }
    },
    'moderately-severe': { 
        en: 'This is a heavy load. It’s okay to not be okay. Reaching out is strength.', 
        es: 'Esta temporada está muy difícil. No tienes que poder con todo solo/a. Buscar apoyo es de valientes.',
        clinical: { en: 'Moderately severe depressive symptoms. Professional intervention recommended.', es: 'Síntomas depresivos moderadamente graves. Se recomienda intervención profesional.' }
    },
    severe: { 
        en: 'You’re in the red zone. Please prioritize yourself today and reach out.', 
        es: 'Estás en una zona difícil. Por favor, haz de tu bienestar la prioridad hoy y busca ayuda.',
        clinical: { en: 'Severe depressive symptoms. Immediate clinical follow-up advised.', es: 'Síntomas depresivos graves. Se aconseja seguimiento clínico inmediato.' }
    }
  },
  anxiety: {
    minimal: { 
        en: 'Your peace seems solid. Keep setting those boundaries.', 
        es: 'Tu calma se ve bien. Sigue poniendo esos límites necesarios.',
        clinical: { en: 'Minimal anxiety symptoms.', es: 'Síntomas de ansiedad mínimos.' }
    },
    mild: { 
        en: 'A little restless? Try some deep breathing to clear the noise.', 
        es: '¿Un poco inquieto/a? Intenta desconectarte un rato y respira profundo.',
        clinical: { en: 'Mild anxiety symptoms.', es: 'Síntomas de ansiedad leves.' }
    },
    moderate: { 
        en: 'The "what-ifs" are taking over. Let’s talk about finding tools.', 
        es: 'La mente no para de dar vueltas. Sería bueno buscar herramientas.',
        clinical: { en: 'Moderate anxiety symptoms. Counseling may be beneficial.', es: 'Síntomas de ansiedad moderados. La consejería puede ser beneficiosa.' }
    },
    severe: { 
        en: 'The anxiety is loud right now. Support is a tool for survival.', 
        es: 'La ansiedad está gritando fuerte. Buscar ayuda es una herramienta para recuperar tu paz.',
        clinical: { en: 'Severe anxiety symptoms. Diagnostic interview recommended.', es: 'Síntomas de ansiedad graves. Se recomienda entrevista diagnóstica.' }
    }
  }
};
